Controllers/VentaController.cs
using iTextSharp.text.pdf;
using iTextSharp.text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using OfficeOpenXml;
using VentasAPP.Models;
using Microsoft.AspNetCore.Authorization;

namespace VentasAPP.Controllers
{
    public class VentaController : Controller
    {
        private readonly VentaService _ventaService;
        private readonly ProductoService _productoService;
        private readonly ILogger<VentaController> _logger;

        // dependencias de servicios y logger
        public VentaController(VentaService ventaService, ProductoService productoService,ILogger<VentaController> logger)
        {
            _ventaService = ventaService;
            _logger = logger;
            _productoService = productoService;
        }

        //  Muestra lista de ventas(solo al Admin)
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(DateTime? fechaDesde,DateTime? fechaHasta,decimal? totalMin,decimal? totalMax, int? userId)
        {
            try
            {
                // Obtiene todas las ventas desde el servicio
                var ventas = await _ventaService.ObtenerTodasLasVentasAsync();

                
                ViewBag.FechaDesde = fechaDesde?.ToString("yyyy-MM-dd");
                ViewBag.FechaHasta = fechaHasta?.ToString("yyyy-MM-dd");
                ViewBag.TotalMin = totalMin;
                ViewBag.TotalMax = totalMax;
                ViewBag.UserId = userId;

                
                if (fechaDesde.HasValue)
                    ventas = ventas.Where(v => v.Fecha.Date >= fechaDesde.Value.Date);
                if (fechaHasta.HasValue)
                    ventas = ventas.Where(v => v.Fecha.Date <= fechaHasta.Value.Date);
                if (totalMin.HasValue)
                    ventas = ventas.Where(v => v.monto_total >= totalMin.Value);
                if (totalMax.HasValue)
                    ventas = ventas.Where(v => v.monto_total <= totalMax.Value);
                if (userId.HasValue)
                    ventas = ventas.Where(v => v.IdUsuario == userId.Value);

                return View(ventas.ToList());
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al obtener la lista de ventas.");
                return View("Error");
            }
        }


        // GET: Venta/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var venta = await _ventaService.ObtenerVentaPorIdAsync(id);
                if (venta == null)
                {
                    return NotFound();
                }
                return View(venta);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al obtener los detalles de la venta con ID {Id}.", id);
                return View("Error");
            }
        }

        // GET: Venta/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Venta/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Venta venta)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var idVenta = await _ventaService.InsertarVentaAsync(venta);
                   
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error al crear una nueva venta.");
                    ModelState.AddModelError("", "No se pudo crear la venta. Inténtalo de nuevo.");
                    return View(venta);
                }
            }
            return View(venta);
        }

        // GET: Venta/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var venta = await _ventaService.ObtenerVentaPorIdAsync(id);
                if (venta == null)
                {
                    return NotFound();
                }
                return View(venta);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al obtener la venta a editar con ID {Id}.", id);
                return View("Error");
            }
        }

        // POST: Venta/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, Venta venta)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _ventaService.ActualizarVentaAsync(id, venta);
                    if (!result)
                    {
                        return NotFound();
                    }
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error al editar la venta con ID {Id}.", id);
                    ModelState.AddModelError("", "No se pudo guardar los cambios. Inténtalo de nuevo.");
                    return View(venta);
                }
            }
            return View(venta);
        }

        // GET: Venta/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var venta = await _ventaService.ObtenerVentaPorIdAsync(id);
                if (venta == null)
                {
                    return NotFound();
                }
                return View(venta);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al obtener la venta a eliminar con ID {Id}.", id);
                return View("Error");
            }
        }

        // POST: Venta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var result = await _ventaService.EliminarVentaAsync(id);
                if (!result)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error al eliminar la venta con ID {Id}.", id);
                return View("Error");
            }
        }


        //Confirma la compra, crea registro y actualiza inventario
        [HttpPost]
        
        public async Task<IActionResult> ConfirmarCompra()
        {
            var carritoStr = HttpContext.Session.GetString("Carrito");
            if (string.IsNullOrEmpty(carritoStr))
                return RedirectToAction("VerCarrito", "Producto");

            var carrito = JsonConvert.DeserializeObject<List<ItemCarrito>>(carritoStr);
            var total = carrito.Sum(x => x.Precio * x.Cantidad);

            var usuarioIdClaim = User.FindFirst("IDUsuario");
            if (usuarioIdClaim == null)
                return RedirectToAction("Login", "Home");
            int usuarioId = int.Parse(usuarioIdClaim.Value);

            
            var venta = new Venta
            {
                IdUsuario = usuarioId,
                monto_total = total,
                metodo_pago = "Efectivo"
            };
            await _ventaService.InsertarVentaAsync(venta);

            
            foreach (var item in carrito)
            {
                
                var prod = await _productoService.ObtenerProductoPorIdAsync(item.ProductoId);
                if (prod == null)
                    continue;

                
                prod.Disponible = Math.Max(0, prod.Disponible - item.Cantidad);

                
                await _productoService.ActualizarProductoAsync(prod.idproducto, prod);
            }

            
            HttpContext.Session.Remove("Carrito");

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Confirmacion");
            }
        }
        public IActionResult Confirmacion()
        {
            return View();
        }

        ////Genera reporte PDF de ventas filtradas
        [HttpGet]
        public async Task<IActionResult> ExportToPdf(
        DateTime? fechaDesde,
        DateTime? fechaHasta,
        decimal? totalMin,
        decimal? totalMax,
        int? userId)
        {
            
            var ventas = await _ventaService.ObtenerTodasLasVentasAsync();
            if (fechaDesde.HasValue) ventas = ventas.Where(v => v.Fecha.Date >= fechaDesde.Value.Date);
            if (fechaHasta.HasValue) ventas = ventas.Where(v => v.Fecha.Date <= fechaHasta.Value.Date);
            if (totalMin.HasValue) ventas = ventas.Where(v => v.monto_total >= totalMin.Value);
            if (totalMax.HasValue) ventas = ventas.Where(v => v.monto_total <= totalMax.Value);
            if (userId.HasValue) ventas = ventas.Where(v => v.IdUsuario == userId.Value);

            using var stream = new MemoryStream();
            var doc = new Document(PageSize.A4, 25, 25, 30, 30);
            PdfWriter.GetInstance(doc, stream).CloseStream = false;
            doc.Open();

            var table = new PdfPTable(3) { WidthPercentage = 100 };
           
            table.AddCell("Total");
            table.AddCell("ID Usuario");
            table.AddCell("Método");

            foreach (var v in ventas)
            {
               
                table.AddCell(v.monto_total.ToString("F2"));

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VentasAPP</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VentasAPP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Login.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
    <style>
        .nav-item {
            margin-right: 20px;
        }

            .nav-item:last-child {
                margin-right: 0;
            }

        .logout-button {
            background-color: #dc3545 !important; /* Rojo Bootstrap */
            color: white !important;
            border-radius: 0.25rem; /* Redondeado de Bootstrap */
            padding: 0.5rem 1rem !important; /* padding de Bootstrap */
            border: none !important;
        }

            .logout-button:hover {
                background-color: #c82333 !important; /* Más oscuro al pasar el mouse */
            }

        .navbar-nav {
            align-items: center; /* Centra verticalmente los items */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">VentasAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <span class="nav-item">Bienvenido, @User.Identity.Name</span>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="Index">Ventas Registradas</a>
                                </li>
                            }
                            else if (User.IsInRole("Cliente"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                                </li>
                            }
                            <li class="nav-item">
                                <form asp-controller="Home" asp-action="Logout" method="post">
                                    <button type="submit" class="btn btn-link nav-link text-dark logout-button">Log Out</button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - VentasAPP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>